import { StyleSheet, Dimensions, Platform } from "react-native";

const { width } = Dimensions.get("window");
import COLORS from "../../../constants/colors";
export { COLORS };
export const ORANGE = "#F97316";
const CAPTURE_BTN = 72;
const CORNER_LEN = 28;

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: "#000" },

  camera: { flex: 1 },
  topBar: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: Platform.OS === "ios" ? 52 : 36,
    paddingBottom: 16,
    backgroundColor: "rgba(0,0,0,0.35)",
  },
  back: { color: "#fff", fontSize: 14, fontWeight: "600" },
  topTitle: { color: "#fff", fontSize: 16, fontWeight: "700" },
  topTime: { color: "#fff", fontSize: 13, fontWeight: "500", opacity: 0.85 },

  modeSwitch: {
    position: "absolute",
    top: Platform.OS === "ios" ? 118 : 102,
    alignSelf: "center",
    flexDirection: "row",
    backgroundColor: "rgba(0,0,0,0.4)",
    borderRadius: 20,
    padding: 3,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.2)",
  },
  modeBtn: { paddingVertical: 7, paddingHorizontal: 20, borderRadius: 17 },
  modeBtnActive: { backgroundColor: COLORS.primary },
  modeBtnText: {
    color: "rgba(255,255,255,0.6)",
    fontSize: 13,
    fontWeight: "600",
  },
  modeBtnTextActive: { color: "#fff" },

  faceFrameWrap: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: "center",
    alignItems: "center",
  },
  faceHint: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "600",
    textAlign: "center",
    marginBottom: 20,
    letterSpacing: 0.2,
  },
  faceFrame: {
    width: width * 0.72,
    height: width * 0.88,
    position: "relative",
  },
  corner: {
    position: "absolute",
    width: CORNER_LEN,
    height: CORNER_LEN,
    borderWidth: 3,
  },
  cornerTL: { top: 0, left: 0, borderRightWidth: 0, borderBottomWidth: 0, borderTopLeftRadius: 3 },
  cornerTR: { top: 0, right: 0, borderLeftWidth: 0, borderBottomWidth: 0, borderTopRightRadius: 3 },
  cornerBL: { bottom: 0, left: 0, borderRightWidth: 0, borderTopWidth: 0, borderBottomLeftRadius: 3 },
  cornerBR: { bottom: 0, right: 0, borderLeftWidth: 0, borderTopWidth: 0, borderBottomRightRadius: 3 },
  processingOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: COLORS.overlayDark,
    justifyContent: "center",
    alignItems: "center",
    gap: 16,
  },
  processingText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
    letterSpacing: 0.3,
  },
  processingSubText: { color: "rgba(255,255,255,0.65)", fontSize: 12 },
  bottomBar: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    paddingHorizontal: 24,
    paddingBottom: Platform.OS === "ios" ? 44 : 32,
    paddingTop: 20,
    backgroundColor: "rgba(0,0,0,0.45)",
    alignItems: "center",
    gap: 16,
  },
  gpsText: { color: "rgba(255,255,255,0.6)", fontSize: 12 },

  captureBtn: {
    width: CAPTURE_BTN,
    height: CAPTURE_BTN,
    borderRadius: CAPTURE_BTN / 2,
    backgroundColor: ORANGE,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: ORANGE,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.45,
    shadowRadius: 10,
    elevation: 8,
  },
  captureBtnLabel: {
    marginTop: 10,
    color: "rgba(255,255,255,0.85)",
    fontSize: 13,
    fontWeight: "600",
    letterSpacing: 0.2,
  },

  resultOverlay: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "rgba(0,0,0,0.55)",
    paddingBottom: Platform.OS === "ios" ? 40 : 28,
  },
  resultCard: {
    margin: 16,
    borderRadius: 20,
    overflow: "hidden",
    backgroundColor: "#fff",
  },
  resultCardSuccess: { backgroundColor: "#fff" },
  resultCardError: { backgroundColor: "#fff" },

  employeeRow: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    gap: 14,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  employeeAvatar: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: COLORS.primaryLight,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: COLORS.primary,
  },
  employeeAvatarText: {
    fontSize: 22,
    fontWeight: "700",
    color: COLORS.primary,
  },
  employeeName: { fontSize: 16, fontWeight: "700", color: COLORS.textDark },
  employeeCode: { fontSize: 12, color: COLORS.textLight, marginTop: 2 },

  statusRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  statusBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
  },
  statusBadgeSuccess: { backgroundColor: COLORS.successLight },
  statusBadgeError: { backgroundColor: COLORS.dangerLight },
  statusDot: { width: 8, height: 8, borderRadius: 4 },
  statusText: { fontSize: 13, fontWeight: "700" },
  statusTextSuccess: { color: COLORS.success },
  statusTextError: { color: COLORS.danger },

  checkinTime: {
    fontSize: 26,
    fontWeight: "800",
    color: COLORS.textDark,
    letterSpacing: -0.5,
  },
  checkinDate: {
    fontSize: 11,
    color: COLORS.textLight,
    textAlign: "right",
    marginTop: 1,
  },

  locationRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 16,
    paddingBottom: 14,
  },
  locationText: { fontSize: 12, color: COLORS.textMid },

  btnRetry: {
    marginHorizontal: 16,
    marginBottom: 16,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: COLORS.border,
    alignItems: "center",
    backgroundColor: COLORS.bg,
  },
  btnRetryText: { color: COLORS.textMid, fontSize: 13, fontWeight: "600" },
  errorMsg: {
    fontSize: 13,
    color: COLORS.danger,
    textAlign: "center",
    paddingHorizontal: 16,
    paddingBottom: 12,
    lineHeight: 20,
  },

  permissionContainer: {
    flex: 1,
    backgroundColor: COLORS.bg,
    justifyContent: "center",
    alignItems: "center",
    padding: 32,
  },
  permissionIcon: { fontSize: 64, marginBottom: 20 },
  permissionTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: COLORS.textDark,
    marginBottom: 8,
    textAlign: "center",
  },
  permissionSub: {
    fontSize: 14,
    color: COLORS.textLight,
    textAlign: "center",
    lineHeight: 22,
    marginBottom: 32,
  },
  btnAllow: {
    backgroundColor: COLORS.primary,
    borderRadius: 14,
    paddingVertical: 15,
    paddingHorizontal: 48,
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 8,
  },
  btnAllowText: { color: "#fff", fontSize: 15, fontWeight: "700" },
});
