version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - DB_SERVER=DESKTOP-I7TARI5
      - DB_USER=technical
      - DB_PASSWORD=123456@Ab
      - DB_NAME=HCNS_MT
      - PORT=3001
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    restart: always
